apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
        app: nginx-deployment
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
        labels: 
          app: nginx-deployment
    spec:
      containers:
      - image: angelomalatacca/nginx-deployment
        name:  nginx-container
        ports:
        - containerPort:  8080
          name:  nginx-web-port
      restartPolicy: Always